#! /usr/bin/env python
#----------------------------------------------------------------------------#
# Python code
# Author: Bruno Turcksin
# Date: 2011-10-21 09:22:37.226201
#----------------------------------------------------------------------------#

print ("\documentclass{beamer}")
print ("\usepackage[T1]{fontenc}")
print ("\usepackage{amsmath}")
print ("\usepackage{color}")
print ("\usepackage{graphicx}")
print ("\usepackage{float}")
print ("\usepackage{lscape}")
print ("\usepackage{multimedia}")
print ("\usepackage{enumerate}")
print ("\usepackage{hyperref}")
print ("")
print ("\usetheme{Frankfurt}")
print ("")
print ("\setbeamertemplate{footline}{")
print ("\leavevmode")
print ("\hbox{\hspace*{-0.06cm}")
print ("\\begin{beamercolorbox}[wd=.35\paperwidth,ht=2.25ex,dp=1ex,center]{author in head/foot}")
print ("\usebeamerfont{author in head/foot}\insertshortauthor")
print ("\end{beamercolorbox}%")
print ("\\begin{beamercolorbox}[wd=.55\paperwidth,ht=2.25ex,dp=1ex,center]{section in head/foot}")
print ("\usebeamerfont{section in head/foot}\insertshorttitle")
print ("\end{beamercolorbox}%")
print ("\\begin{beamercolorbox}[wd=.1\paperwidth,ht=2.25ex,dp=1ex,right]{section in head/foot}")
print ("\usebeamerfont{section in head/foot}\insertframenumber{}/\inserttotalframenumber\hspace*{2ex}")
print ("\end{beamercolorbox}}}")
print ("")
print ("")
print ("\\newcommand\\bn{\\boldsymbol{\\nabla}}")
print ("\\newcommand\\bo{\\boldsymbol{\Omega}}")
print ("\\newcommand\\br{\mathbf{r}}")
print ("\\newcommand\la{\left\langle}")
print ("\\newcommand\\ra{\\right\\rangle}")
print ("\\newcommand\\bs{\\boldsymbol}")
print ("\\newcommand\\red{\\textcolor{red}}")
print ("\\newcommand\ldb{\{\!\!\{}")
print ("\\newcommand\\rdb{\}\!\!\}}")
print ("\\newcommand\llb{\llbracket}")
print ("\\newcommand\\rrb{\\rrbracket}")
print ("")
print ("\\renewcommand{\(}{\left(}")
print ("\\renewcommand{\)}{\\right)}")
print ("\\renewcommand{\[}{\left[}")
print ("\\renewcommand{\]}{\\right]}")
print ("")
print ("\\beamertemplatetransporentcovered")
print ("")
print ("\\title[shorttitle]{longtitle}")
print ("\\author{Bruno Turcksin}")
print ("\institute{Texas A\&M University, Dept. of Nuclear Engineering}")
print ("\date{}")
print ("")
print ("\\begin{document}")
print ("")
print ("\\begin{frame}")
print ("maketitle")
print ("\end{frame}")
print ("%-----------------------------------------------------------------------------")
print ("\logo{\includegraphics[height=0.5cm]{logo_TEXAS.jpg}}")
print ("\\begin{frame}")
print ("\\frametitle{Outline}")
print ("\\tableofcontents[hideallsubsections]")
print ("\end{frame}")
print ("")
print ("\end{document}")
